export const text = {
  en: {
    'queue-lang': 'Queue',
    'watched-lang': 'Watched',
    'zsu': 'Support Ukraine',
    'genr-lang': 'Genres',
    'year-lang': 'Year',
    'year-chose': 'year',
    // 'p-lang': 'popularity',
    // 'popularity-lang': 'Popularity',
    'all-genres-lang': 'all genres',
    // 'most-popular-lang': 'most popular first',
    // 'users-choise-lang': 'users choise first',
    'home': 'HOME',
    'library': 'MY LIBRARY',
    'log-lang': 'Log in',
    "log-out": "Log out",
  }
  , ua: {
    'queue-lang': 'В черзі',
    'watched-lang': 'Переглянуті',
    'zsu': 'Допомога ЗСУ',
    'genr-lang': 'Жанри',
    'year-lang': 'Рік',
    'year-chose': 'рік',
    'p-lang': 'популярні',
    // 'popularity-lang': 'Популярні',
    'all-genres-lang': 'всі жанри',
    // 'most-popular-lang': 'за популярністю',
    // 'users-choise-lang': 'вибір користувача',
    'home': 'ГОЛОВНА',
    'library': 'МОЯ БІБЛІОТЕКА',
    'log-lang': 'УВІЙТИ',
    "log-out": "ВИЙТИ",
  }
};