export const teamItems = [
  {
    photo: 'https://s1.hostingkartinok.com/uploads/images/2022/06/7e29ad82784f09a2d93bc33832fc3b36.jpg',
    name: 'Наша',
    family: 'команда',
    description: '',
    rol: '',
  },
  {
    photo: 'https://ca.slack-edge.com/T02UC9J08RZ-U02V3EY7XD4-110eb73de207-512',
    name: 'Вадим',
    family: 'Гудіма',
    description: 'Підключені номери сторінок (пагінація) на головній сторінці',
    rol: 'Developer',
  },
  {
    photo: 'https://ca.slack-edge.com/T02UC9J08RZ-U02UL6K4J3Z-52ebdd25a53d-512',
    name: 'Влад',
    family: 'Koблай',
    description: 'За натисканням на кнопку "Add to watched" фільм додається до переглянутих фільмів поточного користувача (local-storage)',
    rol: 'Developer',
  },
  {
    photo: 'https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825__340.jpg',
    name: 'Єлла',
    family: 'Кадряєва',
    description: 'Реалізоване модальне вікно "Наша комада"',
    rol: 'Developer',
  },
  {
    photo: 'https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825__340.jpg',
    name: 'Катерина',
    family: 'Клімчук',
    description: 'Реалізоване відображення у картці фільму жанрів, бібліотека користувача "My Library". Зверстано контейнер сторінки "My Library".  ',
    rol: 'Developer',
  },
  {
    photo: 'https://ca.slack-edge.com/T02UC9J08RZ-U02VA0E6P98-7a33fe11371b-512',
    name: 'Уляна ',
    family: 'Комаринська',
    description: 'Реалізований пошук та відображення фільмів за ключовим словом.Підключ Loader (spinner) для асинхронних запитів',
    rol: 'Developer, Scram master',
  },
  {
    photo: 'https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825__340.jpg',
    name: 'Сергій',
    family: 'Кіслинський',
    description: ' Реалізоване відкриття модалки з динамічно підставленою інформацією про фільм та закриття її за натисканням на клавішу ESC.',
    rol: 'Developer',
  },
  {
    photo: 'https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825__340.jpg',
    name: 'Оксана',
    family: 'Олефіренко',
    description: 'Реалізовано підвантаження популярних фільмів на головну (першу) сторінку. Зверстано шаблон картки одного фільму',
    rol: 'Developer',
  },
  {
    photo: 'https://ca.slack-edge.com/T02UC9J08RZ-U03065NDBM1-5d1b6546a14b-512',
    name: 'Инна',
    family: 'Савченко',
    description: 'Зверстано хедер для сторінки "My Library" (мобілка, планшет, робочий стіл)',
    rol: 'Developer',
  },
  {
    photo: 'https://ca.slack-edge.com/T02UC9J08RZ-U02V13GTDA6-3181b03cc28c-512',
    name: 'Кіріл',
    family: 'Мінаєв',
    description: 'За натисканням на кнопку "Watched"/"Queue" показуються переглянуті фільми користувача/ фільми додані в чергу користувача',
    rol: 'Developer',
  },
  {
    photo: 'https://ca.slack-edge.com/T02UC9J08RZ-U030J8LHJBS-17674dec2a10-512',
    name: 'Андрій',
    family: 'Михайленко',
    description: 'Реалізована верстка футера (мобілка, планшет, десктоп). Dark and Light theme switcher.',
    rol: 'Developer, TeamLead',
  },
];
