export const teamItems = [
  {
    photo: '../images/photo-team/photo-4vh.jpg',
    name: 'Vadym',
    family: 'Hudyma',
    description: 'Підключені номери сторінок (пагінація) на головній сторінці',
    rol: 'Developer',
  },
  {
    photo: './photo-team/photo-5vk.jpg',
    name: 'Vlad',
    family: 'Koblay',
    description: 'За натисканням на кнопку "Add to watched" фільм додається до переглянутих фільмів поточного користувача (local-storage)',
    rol: 'Developer',
  },
  {
    photo: './photo-team/photo-6ek.jpg',
    name: 'Єлла',
    family: 'Кадряєва',
    description: 'Модальне вікно Наша комада',
    rol: 'Developer',
  },
  {
    photo: 'https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825__340.jpg',
    name: 'Kateryna',
    family: 'Klimchuk',
    description: '',
    rol: 'Developer',
  },
  {
    photo: './photo-team/photo-1uk.jpg',
    name: 'Уляна ',
    family: 'Комаринська',
    description: 'Реалізуваний пошук та відображення фільмів за ключовим словом',
    rol: 'Developer, Scram master',
  },
  {
    photo: './photo-team/photo-2sk.jpg',
    name: 'Serhii',
    family: 'Kyslynsky',
    description: 'Реалізувано реєстрацію/автентифікацію користувача через Firebase',
    rol: 'Developer',
  },
  {
    photo: 'https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825__340.jpg',
    name: 'Оксана',
    family: 'Олефіренко',
    description: 'Реалізувано підвантаження популярних фільмів на головну (першу) сторінку. Зверстано шаблон картки одного фільму',
    rol: 'Developer',
  },
  {
    photo: './photo-team/photo-3si.jpg',
    name: 'Inna',
    family: 'Savchenko',
    description: 'Зверстано хедер для сторінки "My Library" (мобілка, планшет, робочий стіл)',
    rol: 'Developer',
  },
  {
    photo: 'https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825__340.jpg',
    name: 'Kiril',
    family: 'Minaev',
    description: 'За натисканням на кнопку "Watched" показуються переглянуті фільми користувача. За натисканням на кнопку "Queue" показуються фільми додані в чергу користувача',
    rol: 'Developer',
  },
  {
    photo: 'https://ca.slack-edge.com/T02UC9J08RZ-U030J8LHJBS-17674dec2a10-512',
    name: 'Andrii',
    family: 'Mykhailenko',
    description: 'Верстка футера (мобілка, планшет, десктоп) (однаковий для двох сторінок)',
    rol: 'Developer, TeamLead',
  },
  {
    photo: 'https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825__340.jpg',
    name: 'Anna',
    family: '',
    description: '',
    rol: 'Developer',
  },
];
