export const teamItems = [
  {
    photo: '',
    name: 'Наша',
    family: 'команда',
    description: '',
    rol: '',
  },
  {
    photo: 'images/team/photo-4vh.jpg',
    name: 'Вадим',
    family: 'Гудіма',
    description: 'Підключені номери сторінок (пагінація) на головній сторінці',
    rol: 'Developer',
  },
  {
    photo: 'images/team/photo-5vk.jpg',
    name: 'Влад',
    family: 'Koблай',
    description: 'За натисканням на кнопку "Add to watched" фільм додається до переглянутих фільмів поточного користувача (local-storage)',
    rol: 'Developer',
  },
  {
    photo: 'images/team/photo-6ek.jpg',
    name: 'Єлла',
    family: 'Кадряєва',
    description: 'Реалізоване модальне вікно "Наша комада"',
    rol: 'Developer',
  },
  {
    photo: 'https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825__340.jpg',
    name: 'Катерина',
    family: 'Клімчук',
    description: 'Реалізоване відображення у картці фільму жанрів, бібліотека користувача "My Library". Зверстано контейнер сторінки "My Library".  ',
    rol: 'Developer',
  },
  {
    photo: 'images/team/photo-1uk.jpg',
    name: 'Уляна ',
    family: 'Комаринська',
    description: 'Реалізований пошук та відображення фільмів за ключовим словом.Підключ Loader (spinner) для асинхронних запитів',
    rol: 'Developer, Scram master',
  },
  {
    photo: 'images/team/photo-2sk.jpg',
    name: 'Сергій',
    family: 'Кіслинський',
    description: ' Реалізоване відкриття модалки з динамічно підставленою інформацією про фільм та закриття її за натисканням на клавішу ESC.',
    rol: 'Developer',
  },
  {
    photo: 'https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825__340.jpg',
    name: 'Оксана',
    family: 'Олефіренко',
    description: 'Реалізовано підвантаження популярних фільмів на головну (першу) сторінку. Зверстано шаблон картки одного фільму',
    rol: 'Developer',
  },
  {
    photo: 'images/team/photo-3si.jpg',
    name: 'Инна',
    family: 'Савченко',
    description: 'Зверстано хедер для сторінки "My Library" (мобілка, планшет, робочий стіл)',
    rol: 'Developer',
  },
  {
    photo: 'https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825__340.jpg',
    name: 'Кирило',
    family: 'Мінаєв',
    description: 'За натисканням на кнопку "Watched"/"Queue" показуються переглянуті фільми користувача/ фільми додані в чергу користувача',
    rol: 'Developer',
  },
  {
    photo: 'https://ca.slack-edge.com/T02UC9J08RZ-U030J8LHJBS-17674dec2a10-512',
    name: 'Андрій',
    family: 'Михайленко',
    description: 'Реалізована верстка футера (мобілка, планшет, десктоп). Dark and Light theme switcher.',
    rol: 'Developer, TeamLead',
  },
];
