import './sass/main.scss';
import './js/get-movies';
import './js/insert-movies';
import './js/theme';
import './js/loader';
import './js/team';
// import './js/modal-team';
// import './js/modal-items';
import './js/movie-genres';
import './js/search-movies';
import './js/refs';
import './js/pagination';
import './js/film-modal';
import './js/home-library-btns';
import './js/render-local-movies';
import './js/search-form';
import './js/header-mylib';